PSPNFNS:
  valid_explainers: [limers, EFM_Exp, MTER_Exp]
FA:
  valid_explainers: [limers, EFM_Exp, MTER_Exp, ALS]
RA:
  valid_explainers: [limers, EFM_Exp, MTER_Exp, ALS]
diversity:
  valid_explainers: [limers, EFM_Exp, MTER_Exp, ALS, PHI4MF, EMF]
PrecisionRecall:
  valid_explainers: [limers, EFM_Exp, MTER_Exp]
PGF:
  valid_explainers: [ALS, PHI4MF, EMF]
MEP:
  valid_explainers: [PHI4MF, EFM_Exp]
EnDCG:
  valid_explainers: [PHI4MF, EFM_Exp]