PSPNFNS:
  valid_explainers: [limers, EFM_Exp, MTER_Exp]
FA:
  valid_explainers: [limers, EFM_Exp, MTER_Exp, ALS]
RA:
  valid_explainers: [limers, EFM_Exp, MTER_Exp, ALS]
diversity:
  valid_explainers: [limers, EFM_Exp, MTER_Exp, ALS, PHI4MF, EMF]
PrecisionRecall:
  valid_explainers: [limers, EFM_Exp, MTER_Exp]
PGF:
  valid_explainers: [ALS, PHI4MF, EMF]
MEP: # can be used to MF models withedge_weight_matrix
  valid_explainers: [PHI4MF, EMF]
EnDCG: # can be used to MF models withedge_weight_matrix
  valid_explainers: [PHI4MF, EMF]