Exp_LIMERS:
  valid_recommenders: [fm_regressor]
Exp_EFM_Mod:
  valid_recommenders: [EFM]
Exp_EFM:
  valid_recommenders: [EFM]
Exp_MTER:
  valid_recommenders: [MTER]
Exp_ALS:
  valid_recommenders: [ALS]
Exp_PHI4MF:
  valid_recommenders: [MF, EMF, NEMF]
Exp_EMF:
  valid_recommenders: [EMF, NEMF]

