Exp_LIMERS:
  valid_recommenders: [FMRec]
Exp_EFM_Mod:
  valid_recommenders: [EFM, ComparERObj]
Exp_EFM:
  valid_recommenders: [EFM, ComparERObj]
Exp_MTER:
  valid_recommenders: [MTER, ComparERSub]
Exp_ALS:
  valid_recommenders: [ALS]
Exp_PHI4MF:
  valid_recommenders: [MF, EMF, NEMF, LRPPM]
Exp_SU4EMF:
  valid_recommenders: [EMF, NEMF]
Exp_EMF:
  valid_recommenders: [EMF]
Exp_NEMF:
  valid_recommenders: [NEMF]
Exp_NARRE:
  valid_recommenders: [NARRE]
Exp_TriRank:
  valid_recommenders: [TriRank]
