Exp_LIMERS:
  valid_recommenders: [FMRec]
Exp_EFM_Mod:
  valid_recommenders: [EFM]
Exp_EFM:
  valid_recommenders: [EFM]
Exp_Counter:
  valid_recommenders: [EFM, MTER]
Exp_ComparERObj_Mod:
  valid_recommenders: [ComparERObj]
Exp_ComparERObj:
  valid_recommenders: [ComparERObj]
Exp_MTER:
  valid_recommenders: [MTER]
Exp_ComparERSub:
  valid_recommenders: [ComparERSub]
Exp_ALS:
  valid_recommenders: [ALS]
Exp_PHI4MF:
  valid_recommenders: [MF, EMF, NEMF, LRPPM]
Exp_SU4EMF:
  valid_recommenders: [EMF, NEMF]
Exp_EMF:
  valid_recommenders: [EMF]
Exp_NEMF:
  valid_recommenders: [NEMF]
Exp_NARRE:
  valid_recommenders: [NARRE]
Exp_TriRank:
  valid_recommenders: [TriRank]
Exp_PRINCE:
  valid_recommenders: [C2PF, PCRL, MCF]
